dist: trusty
language: c
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
    packages:
      - gcc-6
      - clang-4.0
      - valgrind

env:
  - MATRIX_CC="gcc-6"
  - MATRIX_CC="clang-4.0"

install:
  - curl -L "https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip" -o "ninja-linux.zip"
  - mkdir -p "$HOME/.local/bin"
  - unzip "ninja-linux.zip" -d "$HOME/.local/bin"
  - chmod 755 "$HOME/.local/bin/ninja"
  - pip3 install meson

script:
  - export PATH="$HOME/.local/bin:$PATH"
  - export CC=${MATRIX_CC}
  - export CFLAGS="-Werror -Wno-unused-parameter $CFLAGS"
  - meson "build" --buildtype debugoptimized --warnlevel 2
  - ninja -C "build"
  - ( cd "build" && mesontest )
  - ( cd "build" && TEST_VALGRIND=1 mesontest "--wrap=valgrind --gen-suppressions=all --trace-children=yes --leak-check=full --error-exitcode=1" )

after_failure:
  - cat build/meson-logs/*.txt
